version: '2.3'
services:
  mcsserviciorenhice1:
    image: reposdocker.minsa.gob.pe/mcs-servicio-renhice:1.0.0
    container_name: mcsserviciorenhice1
    hostname: mcsserviciorenhice1
    dns:
      - 10.10.2.6
      - 10.10.3.6
    ports:
      - "17080:8080"
    volumes:
      - "./mcs-minsa:/opt/data/mcs-minsa"
    cpus: 3.6
    cpuset: '0-3'
    restart: always
    mem_limit: '8192m'
    networks:
      testnetwork:
        ipv4_address: 11.11.1.2

networks:
  testnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 11.11.1.0/24
          gateway: 11.11.1.254
